### ISSUE TITLE
Error server unreachable

### ISSUE THREAD

**Issue by novakin** [polytan02/rainloop_ynh#2]
Hi,

I get the following error : server unreachable while installing standard rainloop on a remote server i can access to my yunohost server emails

any idea ?

**Comment by polytan02** [comment]
Have you installed rainloop and connected via admin/12345 to configure your domain ?                                                                                                                                                                                                                                                                           Maxime                                                                                                                                                                                                                 De: NovakinEnvoyé: mercredi 11 février 2015 07:41À: polytan02/rainloop_ynhRépondre à: polytan02/rainloop_ynhObjet: [rainloop_ynh] Error server unreachable (#2)Hi,

I get the following error : server unreachable while installing standard rainloop on a remote server i can access to my yunohost server emails

any idea ?

—Reply to this email directly or view it on GitHub.

**Comment by novakin** [comment]
Damn, I was sure i did it, looks like i didnt update the modifiations, works like a charm :)
