### ISSUE TITLE
Social connector

### ISSUE THREAD

**Issue by alextux** [polytan02/rainloop_ynh#4]
Hi,

I try Facebook and Google social connector in admin parameters but it didn't work when à try to conncet to this services into my rainloop account. I have followed this tutorial http://www.rainloop.net/docs/social/.

Thanks

**Comment by polytan02** [comment]
Sorry but I cannot help for this, this is just a package to install rainloop in yunohost.

Have you checked that the latest version of rainloop is installed ? For this you need to connect in admin in the rainloop web interface and check in the about section.
