### ISSUE TITLE
Installation incomplète

### ISSUE THREAD

**Issue by maniackcrudelis** [polytan02/rainloop_ynh#5]
Bonjour,

je suis en train de m'intéresser à rainloop pour remplacer roundcube. Mais l'installation n'est pas complète et j'ai mis un peu de temps déjà à comprendre que le couple admin:12345 nécessitait de changer de page de login.
Ensuite, je n'ai trouvé aucune référence à ldap, qui me semble pourtant indispensable pour un webmail sur yunohost.
La configuration de base me semble assez simple (mais de toute évidence ce n'est certainement pas le cas pour Madame Michu), pour autant, il m'est impossible de me connecter avec mon user courant.

As-tu rencontré des problèmes particuliers pour la configuration de base de rainloop? Est-il envisageable de préconfigurer l'application afin d'avoir un package prêt à l'emploi pour n'importe qui?

**Comment by polytan02** [comment]
Bonjour à toi,

J'ai tenté d'automatisé l'installation de rainloop, mais je n'ai pas réussi, même à coup de cURL.
Il semble que lors de la première connexion à domain.tld/rainloop/?admin il y ait du code javascript qui fasse deux ou trois trucs.

Concernant la configuration, le plus simple que j'ai fait est le suivant : 
En tant qu'admin, se connecter à domain.tld/?admin avec admin 12345
Ensuite, ajouter un domaine de base (domain.tld dans cet exemple)

Enfin, dans l'onglet domaines, cliques sur ton domaine et renseigne pour le smtp domain.tld (au lieu de smtp.domain.tld) et pour imap idem (donc domain.tld au lieu de imap.domain.tld).

Coche bien "use short login", fait un test et normalement ça roule tout seul !

Qu'en penses-tu ?

J'avoue qu'il serait super d'automatiser tout cela, mais je n'ai pas réussi.

On peut travailler à deux là-dessus si tu le souhaites ?

**Comment by maniackcrudelis** [comment]
Renseigner le nom de domaine ne fonctionne sur un serveur de test (sans dns renseigné), et pour cause, cela oblige rainloop à se connecter à un dns pour revenir là où il se trouve.
Localhost pour l'imap et le smtp sont suffisant et universel.
Et pas besoin d'authentification.

Rainloop m'intéresse beaucoup, ne serait-ce que pour sa capacité à relever également d'autres boîtes mail ! (ça déchire ça !)
Donc ce serait avec plaisir que je pourrais t'aider à faire ce package.
Je dois toutefois terminer préalablement un package pour Teampass sur lequel on travaille avec Ackak et Matlink. Il est en bonne voie de finalisation.

**Comment by polytan02** [comment]
Ok, on en reparle dès que tu es dispo du coup ;)

**Comment by maniackcrudelis** [comment]
En passant,

On a pris l'habitude de travailler sur un kanboard pour organiser les tâches, les suivre et échanger facilement sur chacune d'elle. C'est très pratique.

Je t'envoi les infos nécessaire pour te connecter et aller voir.
https://crudelis.fr/lutim/mCgJ72i7
Lien valable 24h seulement...

**Comment by maniackcrudelis** [comment]
Salut,

Non pas qu'on en ai fini avec Teampass, mais nous sommes bloqué par des erreurs inhérentes au code du logiciel lui-même. Donc pour le moment, Teampass est en attente du développeur principal.

Ce faisant, je peux revenir vers toi pour Rainloop. As-tu vu mon précédent messages et les infos de l'image?

**Comment by maniackcrudelis** [comment]
J'ai forké pour travailler.
https://github.com/maniackcrudelis/rainloop_ynh

Tu peux déjà tester, la config est faite automatiquement et ça fonctionne sans passer par l'admin.
