### ISSUE TITLE
Rainloop libre

### ISSUE THREAD

**Issue by maniackcrudelis** [polytan02/rainloop_ynh#6]
Rainloop est sur une license Creative Commons, qui n'est pas libre.
Et même si le code est open source, il est extrêmement verrouillé à l'usage.

Il m'a notamment été impossible d'intégrer l'adresse carddav, ainsi que les adresses secondaires des utilisateurs, car tout est chiffré et doit être stocké de la même manière.
Et surtout, plus grave à mon goût, j'ai été dans l'impossibilité d'ajouter un lien vers la page de login admin sur la page de login user. Car le code de la page, bien que disponible ne peut pas être modifié. Toute modification du fichier html source reste sans effet sur l'affichage de la page.

Le tout bien sûr, sans documentation...

Rainloop est intéressant mais cet aspect verrouillé ne présage rien de bon.
Une version libre, sous une licence vraiment libre, doit voir le jour.
https://github.com/RainLoop/rainloop-webmail/issues/625

J'attends de voir ce que ça donnera.
Je vais terminer ce package, puisque je l'ai déjà bien avancé. Mais pour le moment, je pense qu'il n'a pas sa place dans Yunohost en l'état.

**Comment by polytan02** [comment]
Salut Maniack,

Je suis d'accord avec toi et c'est aussi pour ça que je n'ai pas poussé l'intégration plus loin.

D'ailleurs, les gars de YunoHost sur le salon XMPP ont également le même point de vue.

Cependant, comment faire pour que j'intègre tes modifications, en gardant trace de ton coup de main, pour MAJ le paquet rainloop_ynh ?

Je pourrais simplement copier les modifications et les intégrer à la main mais j'aurais préféré faire ça avec toi pour qu'on voit qu'on a "travaillé" ensemble. Si cela te dit.

Qu'en penses-tu ?

**Comment by maniackcrudelis** [comment]
Je peux faire un pull request maintenant si tu veux.
Là j'essaye de changer proprement le mot de passe (c'est pas gagné!)

Ensuite je passe la source en tar.gz, c'est rapide et j'ajuste le manifest et le readme.
Je pensais donc faire un pull une fois tout ça terminé.
Enfin, à la base, je pensais faire des PR régulier en travaillant à deux ;) Mais je t'ai pas vu repasser jusqu'à aujourd'hui.

**Comment by polytan02** [comment]
Désolé, j'ai beaucoup de boulot en ce moment :) 

J'ai vu deux ou trois trucs qu'il faudra tester dans différent cas parce que ça doit rester générique.
Egalement, je n'avais pas compris qu'on pouvait utiliser localhost comme nom de domaine, moi j'utilisais ... le nom de domaine justement. Mais ça me semble mieux de faire comme tu proposes.

Sait-on si le logiciel envoie des données à l'extérieur lorsqu'on l'utilise ?

Sais-tu comment activer le SSO pour éviter d'avoir à se reconnecter quand on arrive sur le portail ?

**Comment by maniackcrudelis** [comment]
Je n'ai trouvé aucune info pour se connecter en http auth.

Pour les données envoyées à l'extérieur, j'ai vérifié (je ne suis pas infaillible en la matière) et je n'ai rien vu sortir. A première vue, le code est clean de ce côté là.

**Comment by polytan02** [comment]
Pour le SSO, j'avais vu ça : 
https://github.com/RainLoop/rainloop-webmail/wiki/SSO-example
https://github.com/RainLoop/rainloop-webmail/issues/103

... mais comme je ne suis pas développeur, ça dépasse mes compétences malheureusement.

Comment peut-on travailler ensemble de manière simple et efficace ?

**Comment by maniackcrudelis** [comment]
Je comprend pas trop ce que fait ce code. Le php c'est pas ma tasse de thé...

Comment? Avec les infos que je t'avais envoyé. Un kanboard et une adresse jabber. C'est qu'on utilise avec d'autres et c'est plutôt efficace.
Mais comme je te l'ai dit, je vais terminer les pti trucs qui reste et après j'attends de voir. En l'état rainloop n'est pas prêt pour le grand public. Ne serais-ce que pour le mot de passe 12345 et le login admin impossible à trouver pour un novice.

**Comment by polytan02** [comment]
Ne serais-ce que pour le mot de passe 12345 et le login admin impossible à trouver pour un novice : Mais justement, ne peut-on pas by-passer cela en demande à l'installation un login admi et un mot de passe admin ?
Ensuite on laisse faire rainloop pour s'installer (avec la ligne cURL que tu proposes) et on modifie après-coup avec les infos renseignées par l'utilisateur à l'installation ?

**Comment by maniackcrudelis** [comment]
Le mot de passe j'y travaille en ce moment, ça devrait aller c'est un hash md5 avec le salt de SALT.php et une variable qui me reste à définir.
Pour le login admin, je parlais de la page de login de l'admin sur ?admin.
Moi même à la première install de ton package je me suis retrouvé comme un con avec mon login qui passait pas.

**Comment by polytan02** [comment]
ah, je comprends. Tu veux dire aller sur domain.tld/?admin pour te logger en admin.

**Comment by maniackcrudelis** [comment]
Oui c'est ça. Quand tu le sais ça va.
Mais pour le grand public, c'est l'assurance d'une config qui sera jamais touchée car jamais trouvée.
C'est pour cette raison que je voulais ajouter un lien sur la page de login admin. Mais rien n'est modifiable...

**Comment by polytan02** [comment]
pour le mot de passe, je comprends que la hash est fait de salt+sValue.

Est-ce que tu penses que sValue est "software value" soit la version du logiciel ?

**Comment by maniackcrudelis** [comment]
Ah, moi je l'ai trouvé ici
https://github.com/RainLoop/rainloop-webmail/blob/master/rainloop/v/0.0.0/app/libraries/RainLoop/Config/Application.php#L32

**Comment by polytan02** [comment]
Ah ok, moi je regardais dans le javascript de la page web (admin.js)

**Comment by almereyda** [comment]
> Une version libre, sous une licence vraiment libre, doit voir le jour.

Il y a deux jours depuis Rainloop à une version communautaire dans AGPL v3
https://github.com/RainLoop/rainloop-webmail/issues/8#issuecomment-100014417

**Comment by polytan02** [comment]
Les dernières versions de ce script rainloop_ynh utilisent les sources communautaires : 

https://github.com/polytan02/rainloop_ynh/commit/42106a3be57e522d1819b85e894f0a729dff974b

Cela ne simplifie toujours pas l'installation.
