### ISSUE TITLE
welcome to nginx on debian

### ISSUE THREAD

**Issue by adrien80080** [polytan02/rainloop_ynh#8]
Bonjour !
j'ain installé Rainloop à la racine du domaine (ex : mail.domain.tld)
sauf que j'ai pas la page de rainloop, j'ai la page de NGinx : https://img.abhd.fr/ScCbzGGW/9Mc0WSY7

Je ne sais pas d'ou ça peut venir :/
Une idée ?

**Comment by polytan02** [comment]
Merci, je viens de corriger (normalement)

https://github.com/polytan02/rainloop_ynh/commit/ee269003bb6c99164f0f5b9515c19635a5e6b035
